api:
  encryption:
    key: 3yTY0wFp385R4WvUceLzoGjCl3RiWO8pB7S5xY5G/QA=
esp32:
  board: esp32dev
  framework:
    type: arduino
esphome:
  friendly_name: ESP32 p
  name: p
logger:
  level: DEBUG
ota:
  password: votre_mot_de_passe_ota
  platform: esphome
sensor:
- attenuation: 12db
  filters:
  - median:
      send_every: 1
      send_first_at: 1
      window_size: 5
  id: tension_capteur_1
  name: Tension Capteur 1 (p)
  pin: GPIO32
  platform: adc
  unit_of_measurement: V
  update_interval: 5s
wifi:
  ap:
    password: pv3VYxQMKQUE
    ssid: p Fallback Hotspot
  fast_connect: true
  manual_ip:
    gateway: 192.168.0.1
    static_ip: 192.168.0.100
    subnet: 255.255.255.0
  password: Totoland27190
  reboot_timeout: 0s
  ssid: grattePas_laWiffi
