api:
  encryption:
    key: '!secret api_key'
esp32:
  board: esp32dev
  framework:
    type: arduino
esphome:
  friendly_name: ESP32 t1
  name: t1
logger: {}
ota:
  password: '!secret ota_password'
  platform: esphome
sensor:
- attenuation: 12db
  filters:
  - median:
      send_every: 1
      send_first_at: 1
      window_size: 5
  id: tension_capteur_1
  name: Tension Capteur 1 (t1)
  pin: GPIO32
  platform: adc
  unit_of_measurement: V
  update_interval: 5s
- attenuation: 12db
  filters:
  - median:
      send_every: 1
      send_first_at: 1
      window_size: 5
  id: tension_capteur_2
  name: Tension Capteur 2 (t1)
  pin: GPIO33
  platform: adc
  unit_of_measurement: V
  update_interval: 5s
- attenuation: 12db
  filters:
  - median:
      send_every: 1
      send_first_at: 1
      window_size: 5
  id: tension_capteur_3
  name: Tension Capteur 3 (t1)
  pin: GPIO34
  platform: adc
  unit_of_measurement: V
  update_interval: 5s
- attenuation: 12db
  filters:
  - median:
      send_every: 1
      send_first_at: 1
      window_size: 5
  id: tension_capteur_4
  name: Tension Capteur 4 (t1)
  pin: GPIO35
  platform: adc
  unit_of_measurement: V
  update_interval: 5s
- attenuation: 12db
  filters:
  - median:
      send_every: 1
      send_first_at: 1
      window_size: 5
  id: tension_capteur_5
  name: Tension Capteur 5 (t1)
  pin: GPIO36
  platform: adc
  unit_of_measurement: V
  update_interval: 5s
- attenuation: 12db
  filters:
  - median:
      send_every: 1
      send_first_at: 1
      window_size: 5
  id: tension_capteur_6
  name: Tension Capteur 6 (t1)
  pin: GPIO39
  platform: adc
  unit_of_measurement: V
  update_interval: 5s
wifi:
  ap:
    password: pv3VYxQMKQUE
    ssid: t1 Fallback Hotspot
  fast_connect: true
  manual_ip:
    gateway: 192.168.0.1
    static_ip: 192.168.0.100
    subnet: 255.255.255.0
  password: '!secret wifi_password'
  reboot_timeout: 0s
  ssid: '!secret wifi_ssid'
